[versions]
agp = "8.2.1"
kotlin = "1.9.22"
detekt = "1.18.1"
spotless = "6.23.3"
qodana = "2023.3.1"
protobuf = "0.9.4"
hilt = "2.50"

activity = "1.8.2"
compose-material3 = "1.1.2"
compose = "1.5.4"
datastore = "1.0.0"
hilt-navigation = "1.1.0"
lifecycle = "2.7.0"
material = "1.11.0"

protobuf-javalite = "3.19.1"

timber = "5.0.1"

junit = "4.13.2"
kotlin-coroutines-test = "1.7.3"
test-core = "1.5.0"
robolectric = "4.11.1"

androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
annotation-jvm = "1.7.1"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
io-gitlab-arturbosch-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
protobuf =  { id = "com.google.protobuf", version.ref = "protobuf" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

[libraries]
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
material3 = { group = "com.google.android.material", name = "material", version.ref = "material" }

protobuf-javalite = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protobuf-javalite" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlin-coroutines-test" }
test-core = { group = "androidx.test", name = "core", version.ref = "test-core" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }

androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotation-jvm" }

[bundles]

